### ISSUE TITLE
TimeoutError when executing HTTP requests in analytics_reporter.py

### ISSUE THREAD

**Issue by mindbreaker** [zyxware/ua-archive#5]
### Description
I encountering a `TimeoutError` when the script, which fetches data using the Google Analytics API, runs for multiple hours. This issue does not appear immediately but develops after the script has been operational for a lengthy period, affecting our ability to generate reliable, timely reports.

### Error Message

```
2024-05-22 15:18:41,258 - ERROR - An error occurred while fetching data: The read operation timed out
2024-05-22 15:18:41,311 - ERROR - Traceback (most recent call last):
  File "C:\Users\Desktop\ua-archive\analytics_reporter.py", line 98, in generate_report
    data, next_page_token = get_data(api_key, view_id, dimensions, metrics, start_date, end_date, format_date, page_size, next_page_token, sampling_level, metrics_filter)
  File "C:\Users\Desktop\ua-archive\ga_data_fetcher.py", line 39, in get_data
    ).execute()
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\googleapiclient\http.py", line 222, in _retry_request
    raise exception
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\oauth2client\transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\oauth2client\transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httplib2\__init__.py", line 1724, in request
    (response, content) = self._request(
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httplib2\__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httplib2\__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

```

**Comment by vimaljoseph** [comment]
I've pushed some updates to develop branch, where I created a wrapper script ua-backup.py - to avoid sampling by splitting the entire date range to shorter period - day, week, month or year and execute analytics_reporter.py for the shorter date range. - This may help mitigate this issue. The code on develop is not tested fully. Need help in testing that.

the script merge_reports.py will merge the output CSVs generated back to a single csv file (per report).

Please check and let me know.

**Comment by vimaljoseph** [comment]
Fixed minor issues in the merge script and merged the develop to master. The latest master have the code that will allow you to query UA API by splitting the date range into smaller chunks.
